### ISSUE TITLE
not working in HASS OS   Core 2021.11.5

### ISSUE THREAD

**Issue by pepelillo** [Imperial-Guard/Marantz_TCP#2]
Not working.....
Directories copied as described (I guess in Supervisor Container) where the configuration directory is.
Logs:
2021-11-30 20:30:11 WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify Marantz to extend MediaPlayerEntity
2021-11-30 20:30:16 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up marantztcp platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/marantztcp/media_player.py", line 51, in setup_platform
    from marantz_receiver import MarantzReceiver
ModuleNotFoundError: No module named 'marantz_receiver'

Any help?

**Comment by Imperial-Guard** [comment]
You're right, I didn't updated my github version. I've made some changes which should be working.
